# Generated by Django 4.2.16 on 2024-12-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendship_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='blocked',
        ),
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='pending', max_length=10),
        ),
    ]
