# Generated by Django 4.2.16 on 2024-12-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_friendship_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='blocked',
        ),
    ]
