# Generated by Django 4.2.16 on 2024-12-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_friendrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
