services:
  front-end:
    depends_on:
      - backend
    build:
      context: ./front-end
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./front-end:/usr/share/nginx/html
      - ./front-end/nginx.conf:/etc/nginx/nginx.conf

  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings
      - POSTGRES_DB=bugfreetranscendanceDB
      - POSTGRES_USER=ayoub
      - POSTGRES_PASSWORD=ayoubayoub
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    command: >
      sh -c "redis-server --daemonize yes &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bugfreetranscendanceDB
      POSTGRES_USER: ayoub
      POSTGRES_PASSWORD: ayoubayoub
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
