# Generated by Django 4.2.16 on 2025-01-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_history_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='session_name',
            field=models.CharField(default='session_game', max_length=100),
        ),
    ]
