# Generated by Django 4.2.16 on 2025-01-11 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_history_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date_game',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='history',
            name='scorePlayer1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='scorePlayer2',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
