# Generated by Django 4.2.16 on 2025-01-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_history_achievements_alter_history_scoreplayer2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='achievements',
        ),
    ]
