# Generated by Django 4.2.16 on 2025-01-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_history_achievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='scorePlayer2',
            new_name='opponentScore',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='player1',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='scorePlayer1',
            new_name='playerScore',
        ),
        migrations.RemoveField(
            model_name='history',
            name='player2',
        ),
        migrations.AddField(
            model_name='history',
            name='opponent',
            field=models.IntegerField(default=0),
        ),
    ]
