# Generated by Django 4.2.16 on 2025-01-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_typenotify_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='typeNotify',
            field=models.CharField(default='invite-game', max_length=100),
        ),
    ]
