# Generated by Django 4.2.16 on 2024-12-02 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intra_id', models.IntegerField(blank=True, null=True)),
                ('campus', models.CharField(blank=True, max_length=100, null=True)),
                ('pool_month', models.CharField(blank=True, max_length=20, null=True)),
                ('pool_year', models.CharField(blank=True, max_length=10, null=True)),
                ('wallet', models.IntegerField(default=0)),
                ('correction_points', models.IntegerField(default=0)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/intra/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
