# Generated by Django 4.2.16 on 2024-12-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='correction_points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='intra_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pool_month',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pool_year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet',
        ),
    ]
