# Generated by Django 4.2.16 on 2024-12-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_userprofile_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
