# Generated by Django 4.2.16 on 2024-12-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_userprofile_is_2fa_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
