# Generated by Django 4.2.16 on 2024-12-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_userprofile_is_2fa_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
