# Generated by Django 4.2.16 on 2025-01-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0008_userprofile_totp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_session_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="session_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
