# Generated by Django 4.2.16 on 2025-01-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_twofactorverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
