# Generated by Django 4.2.16 on 2024-12-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='owner_identifier',
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='player_identifier',
            field=models.CharField(max_length=20),
        ),
    ]
