# Generated by Django 4.2.16 on 2024-12-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_tournament_owner_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='players_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_size',
            field=models.IntegerField(default=4),
        ),
    ]
