# Generated by Django 4.2.16 on 2024-12-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_tournament_players_count_and_more'),
        ('tournament', '0003_rename_match_round_tournamentmatch_round_and_more'),
    ]

    operations = [
    ]
