# Generated by Django 4.2.16 on 2024-12-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_merge_20241218_2122'),
        ('tournament', '0004_merge_20241219_0128'),
    ]

    operations = [
    ]
