# Generated by Django 4.2.16 on 2024-12-20 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_remove_matchresult_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='match_loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='tournament.tournamentplayer'),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='match_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='tournament.tournamentplayer'),
        ),
    ]
