# Generated by Django 4.2.16 on 2025-01-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_message_options_rename_message_message_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_name",

            field=models.CharField(max_length=40, unique=True),
        ),
    ]
