# Generated by Django 4.2.16 on 2025-01-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_room_room_name'),
        ('chat', '0005_message_room_alter_room_room_name'),
    ]

    operations = [
    ]
