# Generated by Django 4.2.16 on 2025-01-06 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_merge_20250106_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='profile_image',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
